language: c
dist: xenial
sudo: true
addons:
  ssh_known_hosts:
  - almond-dev.stanford.edu
before_install:
  - python -c "import fcntl; fcntl.fcntl(1, fcntl.F_SETFL, 0)"
  - test "$TRAVIS_REPO_SLUG" != "stanford-oval/almond-gnome" || (openssl aes-256-cbc -K $encrypted_9ed9bade8d25_key -iv $encrypted_9ed9bade8d25_iv -in travis/id_rsa.autodeploy.enc -out travis/id_rsa.autodeploy -d)
  - sudo apt-add-repository -y ppa:alexlarsson/flatpak
  - sudo apt-get update -q -y
install:
  - sudo apt-get install -y flatpak-builder elfutils
  - flatpak --user remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  - flatpak --user install -y flathub org.gnome.Sdk//3.32 org.gnome.Platform//3.32 org.freedesktop.Sdk.Extension.openjdk11//18.08
  - curl -O https://crowdie.stanford.edu/flatpak/build-cache.tar.gz
  - tar xf build-cache.tar.gz
  - ./travis/download-deps.py
script:
  - flatpak-builder --ccache --stop-at=almond-gnome --force-clean _app/ edu.stanford.Almond.json
  - flatpak build --env=npm_config_nodedir=/app --env=PYTHONDONTWRITEBYTECODE=1 _app meson --prefix=/app _build
  - flatpak build --env=npm_config_nodedir=/app --env=PYTHONDONTWRITEBYTECODE=1 _app ninja -C _build
  - flatpak build --env=npm_config_nodedir=/app --env=PYTHONDONTWRITEBYTECODE=1 _app ninja -C _build install >/dev/null 2>&1
  - flatpak-builder --finish-only --repo=_repo _app edu.stanford.Almond.json
deploy:
  provider: script
  skip_cleanup: true
  script: ssh -i ./travis/id_rsa.autodeploy flatpak-builder@almond-dev.stanford.edu
  on:
    branch: master
    repo: stanford-oval/almond-gnome
